version: '2'
services:
  sync-app:
    image: sync
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sync-postgresql:5432/sync
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  sync-postgresql:
    extends:
      file: postgresql.yml
      service: sync-postgresql
